### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by uihdff** [Entware-for-kernel-3x/Entware-ng-3x#10]
After running the standard installation, the following errors were displayed.

FATAL: kernel too old
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/profile is different from the conffile in the new package. The new conffile will be placed at /opt/etc/profile-opkg.
 * pkg_run_script: package "entware-opt" postinst script returned status 127.
 * opkg_configure: entware-opt.postinst returned 127.
FATAL: kernel too old
FATAL: kernel too old

The kernel version is 2.6.36.

Does this mean Entware-ng-3x isn't compatible with the current version of Asuswrt-Rmerlin ?

**Comment by zyxmon** [comment]
> The kernel version is 2.6.36.

Entware-3x is a repo for 3.x kernels
