### ISSUE TITLE
Cryptsetup: please compile without --disable-kernel_crypto 

### ISSUE THREAD

**Issue by blackfuel** [Entware-for-kernel-3x/Entware-ng-3x#11]
Now we can use `cryptsetup` to mount Veracrypt and Truecrypt encrypted devices.  

You just need to add one little header file, `include/linux/if_alg.h`, from the Linux kernel source code distribution.  Then it will compile without the `--disable-kernel_crypto` switch.   Thank you.

**Comment by zyxmon** [comment]
https://github.com/Entware-for-kernel-3x/entware-packages-3x/commit/40357642f8f129cda5c640fe78622a96ea02ecb6

Binaries will be available with the next sync with openwrt.
