### ISSUE TITLE
pixelserv-tls package certs do not get installed

### ISSUE THREAD

**Issue by Xentrk** [Entware-for-kernel-3x/Entware-ng-3x#13]
I installed the entware-ng-3x package on dd-wrt so I could get updated ipset version. Previously, I had the entware-ng package installed on dd-wrt.  I also had to reinstall the pixelserv-tls package and some others.  In my logs, I saw this error message in my log file:  pixelserv: Failed to open/read ca.crt.  I looked at my ASUS routers and noticed there is a ca.crt and ca.key file in the /opt/var/cache/pixelserv directory but not in the same directory on DD-WRT. As a work around, I copied  the cert and key from my ASUS router to my DD-WRT.  It is now working as it should.

**Comment by zyxmon** [comment]
`opkg install ca-certificates`
