### ISSUE TITLE
html error for Packages.html file

### ISSUE THREAD

**Issue by crisc2000** [Entware-for-kernel-3x/Entware-ng-3x#19]
hello guys

if you are looking to the html source code of this file
http://cortex-a15.zyxmon.org/binaries/cortex-a15-3x/Packages.html

you will see a <script> loaded between <head> and body. usually the script are loaded either in the head or at the end of the body (if you want to execute them after the DOM is completed)

```
</head>
<script type="text/javascript" src="/js/list.js"></script>
<body>
```
i think that is not standard even i think everything works fine in firefox, but if you try to see the source code firefox will show the text in red

**Comment by zyxmon** [comment]
Script generating Packages.html file is taken from - https://github.com/ryzhovau/ipk-html-indexer
I have contacted the author, he says: "I've checked this HTML page with validator.w3.org before and doesn't seen this type of error."
