### ISSUE TITLE
Request for uci/swconfig

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-for-kernel-3x/Entware-ng-3x#23]
### Package: uci

For existing package: openwrt shell script

- expected behavior: which uci
/opt/bin/uci

- actual behavior:
```
$ opkg install uci
Unknown package 'uci'.
Collected errors:
 * opkg_install_cmd: Cannot install package uci.
$ opkg install swconfig
Unknown package 'swconfig'.
Collected errors:
 * opkg_install_cmd: Cannot install package swconfig.
```

For new package to be added:
- describe killer features of new package,
reading uci configuration files without having to modify openwrt shell scripts

### Platform:
- please, tell us what feed and\or devices are you using.
mipselsf, Asus RT-N56U, hardware revision 1 and 2

**Comment by zyxmon** [comment]
It looks like openwrt/lede specific package. Entware is use not only on openwrt devices.
