### ISSUE TITLE
symlinks post installation have /opt/etc files pointing to /etc/

### ISSUE THREAD

**Issue by amurabito** [Entware-for-kernel-3x/Entware-ng-3x#3]
i have finished the upgrade process to entware-ng-3x. i have noticed that within my /opt/etc/ folder I now have symlinks that point to the original /etc/ files (which to my knowledge are not preserved on reboot). 

I also observe that new users added are still not preserved across reboots (presumably because /etc/passwd is getting modified, and still being used since /opt/etc/passwd is just pointing there is volatile). 

hamal@RT-04A151D3AAD8[/opt/etc] ls -la
drwxr-xr-x   10 root     root          4096 Aug 24 21:43 .
drwxr-xr-x   18 root     root          4096 Aug 14 08:36 ..
lrwxrwxrwx    1 root     root            10 Aug 24 21:22 group -> /etc/group
-rw-r--r--    1 root     root            27 Aug 14 08:36 group.1
lrwxrwxrwx    1 root     root            12 Aug 24 21:26 gshadow -> /etc/gshadow
drwxr-xr-x    2 root     root          4096 Aug 24 21:18 init.d
-rw-r--r--    1 root     root             0 Aug 14 08:36 ld.so.conf
-rwxr-xr-x    1 root     root          6841 Aug 10 17:39 mymotd
-rw-r--r--    1 root     root           282 Aug 14 08:36 nsswitch.conf
-rw-r--r--    1 root     root           148 Aug 24 17:25 opkg.conf
lrwxrwxrwx    1 root     root            11 Aug 24 21:43 passwd -> /etc/passwd
-rw-r--r--    1 root     root           112 Aug 14 08:36 passwd.1
-rwxr-xr-x    1 root     root           471 Jul 20 19:02 profile
-rwxr-xr-x    1 root     root           566 Aug 14 08:36 profile-opkg
lrwxrwxrwx    1 root     root            11 Aug 24 21:26 shadow -> /etc/shadow
-rw-r--r--    1 root     root            42 Aug 24 21:25 shells
-rw-r--r--    1 root     root            42 Aug 14 08:36 shells.1
drwxr-xr-x    2 root     root          4096 Aug 24 21:18 skel
drwx------    2 root     root          4096 Aug 24 08:07 ssh
drwxr-xr-x    3 root     root          4096 Aug 10 16:19 ssl
-r--r-----    1 root     root          3202 Aug 10 20:35 sudoers
drwxr-xr-x    2 root     root          4096 Jul 20 19:02 sudoers.d
-rw-r--r--    1 root     root           589 Jul 20 19:02 xattr.conf

**Comment by zyxmon** [comment]
Entware-3x is installed in /opt that should be a permanent storage.
Please note there are 2 different installation types (standard and alternative) - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki/General-installation-notes
If files are not preserved in /opt - you have selected the wrong media for installation!
