### ISSUE TITLE
Package request: powershell

### ISSUE THREAD

**Issue by diman82** [Entware-for-kernel-3x/Entware-ng-3x#35]
### Package: <name>

For existing package:

- expected behavior: ...
- actual behavior: ...

For new package to be added:
https://github.com/PowerShell/PowerShell/releases
- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:
ARM7 (Netgear R7000) 
- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
To tricky to build in linux - https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md
It's hardly automated by buildroot scripts.
