### ISSUE TITLE
Package request: GNU Zile

### ISSUE THREAD

**Issue by gavinhungry** [Entware-for-kernel-3x/Entware-ng-3x#4]
https://www.gnu.org/software/zile/

> GNU Zile is a text editor development kit, so that you can (relatively) quickly develop your own ideal text editor without reinventing the wheel for many of the common algorithms and data-structures needed to do so.

Also requested on `entware-ng`: https://github.com/Entware-ng/Entware-ng/issues/431

**Comment by zyxmon** [comment]
You can try and test this one - http://entware-3x.zyxmon.org/binaries/x64/test/zile_2.3.24-4_x64-3x.ipk

Please report.

**Comment by gavinhungry** [comment]
@zyxmon,

Works perfectly on my Synology DS1513+. Thanks!
