### ISSUE TITLE
upgrade kernel version

### ISSUE THREAD

**Issue by debiansid** [Entware-for-kernel-3x/Entware-ng-3x#41]
### Package:  linux kernel

is it possible to upgrade kernel to 4.4.x?

thanks

**Comment by zyxmon** [comment]
Do you really need it? I have used Entware on devices running 4.9.x kernels with no problems.

**Comment by debiansid** [comment]
My netgear R7000 Kong build has different kernel , I am not sure ipset from here can work on it.

**Comment by zyxmon** [comment]
Just try ipset from entware. My guess Kong has compiled ipset for his firmware and you can use it.

**Comment by debiansid** [comment]
`bash-4.3# ipset
bash: ipset: command  not found  `

No ipset with kong build.
