### ISSUE TITLE
IPv6 Support for nfs-kernel

### ISSUE THREAD

**Issue by Haringstad** [Entware-for-kernel-3x/Entware-ng-3x#43]
### Package: nfs-kernel-server

For existing package:

- expected behavior: Should listen/respond to IPv6
- actual behavior: Not available on IPv6, does work (NFSv3/NFSv4) on IPv4.

### Platform:

- QNAP TS-419P II
- Linux QNAP419P 3.4.6 #1 Fri Sep 1 11:00:20 CST 2017 armv5tel GNU/Linux

Clients:
- Linux orange-pi-pc 3.4.113-sun8i #18 SMP PREEMPT Thu Jun 15 02:16:06 CEST 2017 armv7l armv7l armv7l GNU/Linux (Orange Pi PC)
- Linux haringstad-pi 4.9.46-v7+ #1032 SMP Wed Aug 30 12:09:14 BST 2017 armv7l GNU/Linux (Raspberry Pi 3B)

IPv6 is fully functional within the network, including DNS (both PTR and AAAA) for all systems. 
A NMAP scan shows availability on IPv4, but not on IPv6. 
Whenever I do setup a nfs-kernel-server on one of the other systems, I can connect with IPv6.

Please advice? And thank you for the hard work! I do love the functionality that you provide with Entware!

**Comment by zyxmon** [comment]
We build nfs-kernel-server with the same options as upstream
https://github.com/openwrt/packages/blob/master/net/nfs-kernel-server/Makefile#L80
Different options in openwrt and entware will lead to a mess. Please ask upstream for ipv6 support.
