### ISSUE TITLE
par2cmdline - not multi-threaded?

### ISSUE THREAD

**Issue by teracow** [Entware-for-kernel-3x/Entware-ng-3x#47]
### Package: par2cmdline

For existing package:

- expected behavior: ...
to use parameter '-t' for multi-thread processing
- actual behavior: ...
this parameter is not present in packaged version

### Platform:
x86/64

Hi zyxmon, I've just noticed that the version of par2cmdline (0.7.4-1) available here is missing the multi-threading option. Would it be possible to include the multi-thread version instead? 

https://github.com/Parchive/par2cmdline

Thank you. :)

**Comment by zyxmon** [comment]
Entware buildroot is based on lede/openwrt buildroot, that does not have openmp support needed for par2cmdline-mt,

**Comment by teracow** [comment]
Ah, no worries. Thank you.
