### ISSUE TITLE
Inadyn - strange description

### ISSUE THREAD

**Issue by crisc2000** [Entware-for-kernel-3x/Entware-ng-3x#48]
### Package: Inadyn

In index.html , software Inadyn current description is "Suitable for embedded systems, written in C."
If you don't know already that is a DDNS client, you can't tell that from the title or description.

So good luck finding a dynamic dns client in Entware if you are a beginner.

### Platform:
Voxel Firmware / Netgear R7800

**Comment by zyxmon** [comment]
You are quite right. Please report upstream. We take packages from openwrt
https://github.com/openwrt/packages/blob/master/net/inadyn/Makefile
