### ISSUE TITLE
Update General installation notes wiki page with MIPS support

### ISSUE THREAD

**Issue by sean-liang** [Entware-for-kernel-3x/Entware-ng-3x#50]
I'm using **Netgear WNDR4300** with **Atheros AR9344** cpu. The ddwrt kernel is Linux **3.18.76** #983 Fri Oct 20 04:14:41 CEST 2017 **mips**.

The original Entware-ng project doesn't support MIPS cpu. And I followed a issue there to this project. It is perfectly fit my router and works like a charm!

But it really did take me some time to check the repositories to find out that MIPS is actually supported since it's not mentioned in the wiki page.

I think update the **General installation notes** page and add MIPS support could help some guy like me to save a lot of time on searching and digging.

**Comment by zyxmon** [comment]
Thanks. Done.
