### ISSUE TITLE
Package Request: Brother Printer drivers, specifically DCP-7040, DCP-7060D

### ISSUE THREAD

**Issue by ian5142** [Entware-for-kernel-3x/Entware-ng-3x#51]
DCP-7040 linux driver can be found here: http://support.brother.com/g/b/downloadtop.aspx?c=ca&lang=en&prod=dcp7040_us_as

DCP-7060D linux driver is here: http://support.brother.com/g/b/downloadtop.aspx?c=ca&lang=en&prod=dcp7060d_all

I am seeking support specifically for MIPS and MIPSEL. I would be running it on a TP-Link WDR3600v1 router, running DD-WRT, usually the latest version.

**Comment by zyxmon** [comment]
Entware does not provide drivers.
