### ISSUE TITLE
Request: kmod-usb-audio

### ISSUE THREAD

**Issue by obiwan-bartek** [Entware-for-kernel-3x/Entware-ng-3x#52]
### Platform: AR71XX (mips)

I am using WNDR3700v2 (mips) with DD-WRT. As far as I know there is no usb audio support in Entware-3x. Please consider adding it.

**Comment by zyxmon** [comment]
Entware is device independent and does not have device dependand kernel modules.
Ask DD-WRT developers for kernel modules.
