### ISSUE TITLE
Package request: libpcap-dev

### ISSUE THREAD

**Issue by ghost** [Entware-for-kernel-3x/Entware-ng-3x#53]
### Package: libpcap-dev

Currently only the libpcap library itself is available. The dev package adds headers, static libraries, and documentation for it. I believe original optware also included both packages.

Without it, anything requiring pcap header files will fail, such as the node pcap package ([example](https://hastebin.com/haraguvafi)).

### Platform:

I am using a mipsel rt-n56u. I believe the package source is available for all arch ([debian](https://packages.debian.org/stretch/libpcap0.8-dev)).

**Comment by zyxmon** [comment]
There are no dev packages in Entware with few exceptions. You are to install headers manually - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation) (modify URL to Entware-3x). Static linking is not supported.
