### ISSUE TITLE
Prevent architecture warnings on non keenle-3x architectures

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-for-kernel-3x/Entware-ng-3x#60]
### Package: opkg

- expected behavior: no warning
- actual behavior: Package ... version ... has no valid architecture, ignoring.

### Platform: padavan rt-n56u

I am not good at ignoring warnings.

Please add some mechanism to prevent these warnings on non `Architecture: keenle-3x` platforms. 

For example 2 separate feeds:
1. **without** keenle-3x architecture packages
2. **with** keenle-3x architecture packages

**Comment by zyxmon** [comment]
> I am not good at ignoring warnings.

You can append the folowing lines to /opt/etc/opkg.conf
```
arch all 100
arch mipsel-3x 150
arch keenle-3x 200
```
You will see no warnings. Some packages will be added to packages list that are designed for other devices and will not work at you router.
It is better to ignore warnings IMHO.
