### ISSUE TITLE
This is recommended for unification with Entware-3x installations on other devices. The action is not mandatory.

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-for-kernel-3x/Entware-ng-3x#61]
### Platform: padavan rt-n56u

After reading: https://translate.google.com/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fforums.zyxmon.org%2Fviewtopic.php%3Fp%3D15556%23p15556&edit-text=
I am wondering what is meant with:

> This is recommended for unification with Entware-3x installations on other devices. The action is not mandatory.

Is "this" referring to the line before?

```
rm /opt/etc/profile
```

Or after?

```
wget -O - http://entware-3x.zyxmon.org/binaries/mipsel/installer/install_std.sh | /bin/sh
```

In other words: what is optional?

a. `remove .../profile`
or 
b. `run .../install_....sh?`

**Comment by zyxmon** [comment]
Online translator interpretaion is not correct here. This refers to busybox.

**Comment by ProBackup-nl** [comment]
@zyxmon `install_std.sh` installs `entware-opt` which depends upon `busybox`. I don't understand the "not mandatory" part.
Would you mind having a look at https://github.com/ProBackup-nl/Entware-ng-3x/wiki/Install-on-Padavan ? Corrections are welcome, as well as hints to verify that one has not ended up at situation "padavan firmware overwriting entware-3x".

**Comment by zyxmon** [comment]
>  I don't understand the "not mandatory" part.

Look here - http://entware-3x.zyxmon.org/binaries/armv7/installer/install_asuswrt.sh 
It is for armv7 & armv8 now. 2 extra packages need to be added for it. Some packages will need additional adjustments when busybox is not installed.
I'll have a look, and probably copy wiki here, if you don't mind.

**Comment by ProBackup-nl** [comment]
@zyxmon I don't mind **at all** when you copy (and improve) the wiki.

At http://entware-3x.zyxmon.org/binaries/armv7/installer/install_asuswrt.sh the only difference I do spot is the addition of:
`/opt/bin/opkg install asuswrt-opt`

> Package: asuswrt-opt
> Version: 1.0-4
> Depends: libc, libssp, librt, libpthread, libgcc, libstdcpp, libpthread, librt, zoneinfo-asia, zoneinfo-europe, findutils, terminfo, locales
> Conflicts: opt-ndmsv2, entware-opt
> Section: libs
> Architecture: armv7-3x
> Installed-Size: 2340
> Filename: asuswrt-opt_1.0-4_armv7-3x.ipk
> Size: 3131
> MD5Sum: 72dbd2304a7d7e89f0962888cb1f4013
> SHA256sum: 2953e9111f1bb9d1016c8902d25333e65886cad9f141d071c893dc701f0e14ed
> Description:  asuswrt-opt is a metapackage to install Entware-3x basic libraries and scripts

versus

> Package: entware-opt
> Version: 1.0-4
> Depends: libc, libssp, librt, libpthread, libgcc, libstdcpp, libpthread, librt, busybox, zoneinfo-asia, zoneinfo-europe, findutils, terminfo, locales
> Conflicts: opt-ndmsv2
> Section: libs
> Architecture: mipsel-3x
> Installed-Size: 2340
> Filename: entware-opt_1.0-4_mipsel-3x.ipk
> Size: 3029
> MD5Sum: eaae85f917335912c14e7ef4e93d2966
> SHA256sum: 6ea115a46d6811f55bed597856587d14822f5fa75da4e072bd0dd9689e830003
> Description:  provides basic toolchain libraries (dummy)
