### ISSUE TITLE
Release notes for .qpkg?

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-for-kernel-3x/Entware-ng-3x#9]
I see that there is a new version of entware-ng-3x released as .qpkg at [http://entware-3x.zyxmon.org/binaries/other/](http://entware-3x.zyxmon.org/binaries/other/).

I am wondering what is new in this release .99 (over .98).

Where can the release notes for the /other/*.qpkg be found?

**Comment by zyxmon** [comment]
https://forum.qnap.com/viewtopic.php?p=599703#p599703

> New toolchain is used for Entware-3x - binutils 2.27, gcc 6.3 and glibc 2.25. Becase of soname change new QPKG is uploaded.
